import type { Metadata } from "next";
import "@/css/global.css";
import "bootstrap/dist/css/bootstrap.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="pretendard text-center">{children}</body>
    </html>
  );
}
